#!/bin/sh /etc/rc.common
START=99
USE_PROCD=1

start_service() {
  procd_open_instance
  procd_set_param command /usr/bin/dnsproxy -p 5353  -u https://185.222.222.222/dns-query -u https://45.11.45.11/dns-query --cache  --cache-min-ttl=3600
  #procd_set_param command /usr/bin/dnsproxy -p 5353 -u https://2a09::/dns-query --cache  --cache-min-ttl=3600
  #procd_append_param command -bar 42 # append command parameters

  # respawn automatically if something died, be careful if you have an alternative process supervisor
  # if process dies sooner than respawn_threshold, it is considered crashed and after 5 retries the service is stopped
  procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}

  procd_set_param limits nofile="2048 2048"  # If you need to set ulimit for your process
  procd_set_param stdout 1 # forward stdout of the command to logd
  procd_set_param stderr 1 # same for stderr
  procd_set_param pidfile /var/run/doh.pid # write a pid file on instance start and remote it on stop
  procd_close_instance
}
